# Generated by Django 5.0.1 on 2024-05-08 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='recruiter',
        ),
        migrations.DeleteModel(
            name='Recruiter',
        ),
    ]
