# Generated by Django 5.0.1 on 2024-05-08 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0002_remove_job_recruiter_delete_recruiter'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.CharField(default=4, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='salary',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
    ]
