# Generated by Django 5.0.1 on 2024-05-12 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0004_job_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='experience',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
